Make camera work
lukaspieper/android_device_lenovo_tb_x704f pull request #3
Opened 2021-05-10 18:24 UTC by coffeinflash

2021-05-10 19:36 UTC, lukaspieper requested changes

2021-05-10 19:36 UTC, lukaspieper commented on TBX704/device.mk
> +PRODUCT_PACKAGES += \
Thank you for creating this pull request, please undo this change as it has nothing to do with the camera.

2021-05-10 19:58 UTC, coffeinflash commented on TBX704/device.mk
> +PRODUCT_PACKAGES += \
done

2021-05-11 14:25 UTC, lukaspieper approved these changes

2021-05-11 14:25 UTC, merged